use_frameworks!

target 'GINLibrary_Example' do
  pod 'GINLibrary', :path => '../'

  target 'GINLibrary_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
